version: '{build}'

image:
  - Visual Studio 2017

branches:
  only:
    - master
    - dev

skip_commits:
  message: /\[skip ci\]/

environment:
  APPVEYOR_NUGET_API_KEY:
    secure: AtKUh7VTiq0BCPftMVX+nkY7Jsz47iYsYR2iWJ3U//cAQwvo0MWuY0A0bbY3kP4L
  APPVEYOR_PERSONAL_ACCESS_TOKEN:
    secure: +823CdXZbrvfhBVAbcsRT/CGVmREYmkH5g5TC8+1HWjGt0SHZtgS4AWVBbeyfzLl
  APPVEYOR_GITHUB_USERNAME: 'EsOsO'
  APPVEYOR_GITHUB_EMAIL:
    secure: qOw7foLVABiwY5Y4Th58VNI8sbyJpNwvkFSI9DFxqII=

before_build:
  - gitversion /l console /output buildserver

build_script:
  - ps: . .\build.ps1

test: false

deploy:
  tag: $(ReleaseVersion)
  description: "# What's new in $(ReleaseVersion)
  $(ReleaseDescription)"
  force_update: true
  draft: false
  prerelease: false
  provider: GitHub
  auth_token:
    secure: +823CdXZbrvfhBVAbcsRT/CGVmREYmkH5g5TC8+1HWjGt0SHZtgS4AWVBbeyfzLl
  on:
    branch: master
